project:
  host: 10.130.1.78
  is-product: false

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.14.104:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 10.130.1.78:8080
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/x_cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

rocketmq:
  name-server: 192.168.14.104:9876;
