project:
  host: 10.130.1.113

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.130.1.37:8848, 10.130.1.112:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 10.130.1.53:8080
  datasource:
    url: jdbc:mysql://${project.host}:3306/x_cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

rocketmq:
  name-server: 10.130.1.37:9876; 10.130.1.112:9876;